name: Deploy Front End to AWS S3
on:
  push:
    branch: 
      -main
jobs:
  deploy:
    runs-on: ubuntu -latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node Js setup
        uses: actions/setup-node@v1
        with: 
          node-version: ${{secrets.node_version}}
        
      - name: Dependancy Installation
        run: yarn install

      - name: App Build
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
         aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
         aws-region: eu-north-1

      - name: Deploy to AWS S3
        run: aws s3 sync build s3://nortel-test  --delete
